packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.11.0
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.23.0
    lint-staged: ^15.5.0
    pnpm: ^10.4.0
    simple-git-hooks: ^2.12.1
    tsup: ^8.4.0
    tsx: ^4.19.3
    typescript: ^5.8.2
    unocss: ^65.5.0
    vite: ^6.2.3
    vitepress: ^2.0.0-alpha.2
  inlined:
    ethers: ^6
  plugin:
    '@shikijs/vitepress-twoslash': ^2.3.2
    esbuild-plugin-globals: ^0.2.0
    unplugin-vue-components: ^28.1.0
    vite-tsconfig-paths: ^5.1.4
    vitepress-plugin-group-icons: ^1.3.5
  react:
    react: ^18.2.0
    react-dom: ^18.2.0
    react-i18next: ^14.1.2
    react-use: ^17.6.0
    valtio: ^2
  style:
    '@iconify-json/svg-spinners': ^1.2.2
    '@unocss/reset': ^65.5.0
  testing:
    vitest: ^3.0.5
  types:
    '@types/jweixin': ^1.0.8
    '@types/lodash': ^4.17.16
    '@types/lodash-es': ^4.17.12
    '@types/node': ^20.11.7
    '@types/react': ^18.2.43
    '@types/react-dom': ^18.2.17
  utils:
    bignumber.js: ^9.1.2
    change-case: ^5.4.4
    colord: ^2.9.3
    css-render: ^0.15.14
    html-parse-stringify: ^3.0.1
    lodash: ^4.17.21
    lodash-es: ^4.17.21
    mitt: ^3.0.1
    p-pipe: ^4.0.0
  vue:
    '@vueuse/core': ^13.0.0
    pinia: ^3.0.1
    vue: ^3.2.29
    vue-demi: latest
