packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.2.1
  '@antfu/ni': ^23.3.1
  '@antfu/utils': ^9.0.0
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/vitepress-twoslash': ^2.3.2
  '@types/jweixin': ^1.0.8
  '@types/lodash': ^4.17.16
  '@types/node': ^20.11.7
  '@types/react': ^18.2.43
  '@types/react-dom': ^18.2.17
  '@unocss/reset': ^65.5.0
  '@vueuse/core': ^13.0.0
  bignumber.js: ^9.1.2
  bumpp: ^10.0.3
  colord: ^2.9.3
  css-render: ^0.15.14
  esbuild-plugin-globals: ^0.2.0
  eslint: ^9.20.1
  ethers: ^6
  floating-vue: ^5.2.2
  html-parse-stringify: ^3.0.1
  lint-staged: ^15.4.3
  lodash: ^4.17.21
  mitt: ^3.0.1
  p-pipe: ^4.0.0
  pinia: ^3.0.1
  pnpm: ^10.4.0
  react: ^18.2.0
  react-dom: ^18.2.0
  react-i18next: ^14.1.2
  react-use: ^17.6.0
  simple-git-hooks: ^2.11.1
  tsup: ^8.4.0
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^65.5.0
  unplugin-vue-components: ^28.1.0
  vite: ^6.1.0
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.2
  vitepress-plugin-group-icons: ^1.3.5
  vitest: ^3.0.5
  vue: ^3.0.0
