export declare const isBrowser: boolean;
export declare const isWeex: boolean;
export declare const weexPlatform: any;
export declare const UA: string | false;
export declare const isIE: boolean | "";
export declare const isIE9: boolean | "";
export declare const isIE11: boolean;
export declare const isEdge: boolean | "";
export declare const isAndroid: boolean;
export declare const isIOS: boolean;
export declare const isChrome: boolean | "";
export declare const isPhantomJS: boolean | "";
export declare const isFF: false | RegExpMatchArray | null;
